# ====================
# User Endpoints
# ====================

# Get all users
GET http://localhost:3000/users
Content-Type: application/json

###

# Get user by ID
GET http://localhost:3000/users/67727f7879035b604eb54171
Content-Type: application/json

###

# Create a new user
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "moran.doe132",
  "email": "moran.doe@example.com",
  "password": "password123"
}

###

# Update a user by ID
PUT http://localhost:3000/users/67727f7879035b604eb54171
Content-Type: application/json

{
  "username": "123123.updated",
  "email": "john.updated@example.com"
}

###

# Delete a user by ID
DELETE http://localhost:3000/users/67713f2a9557b0405a858d8b
Content-Type: application/json

###

# ====================
# Post Endpoints
# ====================

# Get all posts
GET http://localhost:3000/posts
Content-Type: application/json

###

# Get post by ID
GET http://localhost:3000/posts/67727fad79035b604eb54179
Content-Type: application/json

###

# Create a new post
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "My First Post22",
  "content": "This is the content of the first post",
  "sender": "67727f7879035b604eb54171"
}

###

# Update a post by ID
PUT http://localhost:3000/posts/67727fad79035b604eb54179
Content-Type: application/json

{
  "title": "Updated Post",
  "content": "This is the updated content"
}

###

# Delete a post by ID
DELETE http://localhost:3000/posts/67727fad79035b604eb54179
Content-Type: application/json

###

# ====================
# Comment Endpoints
# ====================

# Get all comments
GET http://localhost:3000/comments
Content-Type: application/json

###

# Get comment by ID
GET http://localhost:3000/comments/67727fec79035b604eb54186
Content-Type: application/json

###

# Create a new comment
POST http://localhost:3000/comments
Content-Type: application/json

{
  "post": "67727fb279035b604eb5417b",
  "content": "This is a comment",
  "sender": "67727f7879035b604eb54171"
}

###

# Update a comment by ID
PUT http://localhost:3000/comments/67727fec79035b604eb54186
Content-Type: application/json

{
  "content": "This is the updated comment"
}

###

# Delete a comment by ID
DELETE http://localhost:3000/comments/67727fec79035b604eb54186
Content-Type: application/json
